server:
  port: 8082
#  servlet:
#    context-path: /kafka
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 121.199.78.155:9092         #Kafka的消息中间件服务器
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          configuration:
            security:
              protocol: SASL_PLAINTEXT
            sasl:
              mechanism: PLAIN
      bindings:
        output: #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: test-topic    #消息发往的目的地
          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要
        input:
          destination: test-topic
          content-type: application/json